# Change mustache escape sequence {{=<% %>=}}
name: Push

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        uses: ./.github/actions/test

  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build
        with:
          tags: ${{ github.sha }} latest
          image: "<% image %>"

      - name: Push To Quay
        uses: redhat-actions/push-to-registry@v2
        if: ${{ github.repository == '<% org %>/<% repo %>'}}
        with:
          image: "<% image %>"
          tags: ${{ github.sha }} latest
          registry: quay.io/<% quay_org %>
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Set expiration
        uses: ./.github/actions/set-expiration
        with:
          repository: "<% quay_org %>/<% image %>"
          tag: ${{ github.sha }}
          expiration: +1 week
          token: ${{ secrets.QUAY_OAUTH_TOKEN }}
